package mx.com.lux.control.trabajos.util.constants;

import mx.com.lux.control.trabajos.util.properties.ApplicationPropertyHelper;
import mx.com.lux.control.trabajos.util.properties.SobresPropertyHelper;
import mx.com.lux.control.trabajos.util.properties.TrabajosPropertyHelper;

public class Constants {

	public static Integer CERO_INTEGER = Integer.valueOf( ApplicationPropertyHelper.getProperty( "constante.cero" ) );
	public static Integer UNO_INTEGER = Integer.valueOf( ApplicationPropertyHelper.getProperty( "constante.uno" ) );
	public static final Integer LONGITUD_ID_EMPLEADO = Integer.valueOf( ApplicationPropertyHelper.getProperty( "constante.longitud.id.empleado" ) );
	public static final Integer LONGITUD_TELEFONO_CASA = Integer.valueOf( TrabajosPropertyHelper.getProperty( "trabajos.label.cliente.tel.casa.limit" ) );
	public static final Integer LONGITUD_CODIGO_POSTAL = Integer.valueOf( TrabajosPropertyHelper.getProperty( "trabajos.label.cliente.codigo.limit" ) );
	public static String CERO_STRING = ApplicationPropertyHelper.getProperty( "constante.cero" );
	public static String UNO_STRING = ApplicationPropertyHelper.getProperty( "constante.uno.string" );
	public static String CERO_UNO_STRING = ApplicationPropertyHelper.getProperty( "constante.cero.uno" );
	public static String CADENA_VACIA = "";
	public static String ESPACIO = " ";
	public static String PARAM_USER_LOGGED = "userParam";
	public static String PARAM_CONTACTO_VIEW = "contactoViewParam";
	public static String INFO_PINO_URL = ApplicationPropertyHelper.getProperty( "info.pino.url" );
	public static String AUTORIZACION_URL = ApplicationPropertyHelper.getProperty( "autorizacion.url" );
	public static String AUTORIZACION_ID_EMPRESA = ApplicationPropertyHelper.getProperty( "autorizacion.id.empresa" );
	public static String SYMBOL_PIPE = TrabajosPropertyHelper.getProperty( "symbol.pipe" );
	public static String SYMBOL_AMPERSAND = TrabajosPropertyHelper.getProperty( "symbol.ampersand" );
	public static String SYMBOL_EQUAL = TrabajosPropertyHelper.getProperty( "symbol.equal" );
	public static String SYMBOL_COMA = TrabajosPropertyHelper.getProperty( "symbol.coma" );
	public static String SYMBOL_ARROBA = TrabajosPropertyHelper.getProperty( "symbol.arroba" );
	public static String REG_EXP_PIPE = TrabajosPropertyHelper.getProperty( "reg.exp.pipe" );
	public static String ERROR_RESPONSE_NO_EXISTE_EMPLEADO = TrabajosPropertyHelper.getProperty( "error.response.no.existe.empleado" );
	public static final Integer MENU_INDEX_DATOS_RECETA = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.datos.receta" ) );
	public static final Integer MENU_INDEX_CONSULTA_TRABAJO = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.consulta.trabajo" ) );
	public static final Integer MENU_INDEX_INFO_LAB = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.info.laboratorio" ) );
	public static final Integer MENU_INDEX_DATOS_CLIENTE = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.datos.cliente" ) );
	public static final Integer MENU_INDEX_REPROGRAMAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.reprogramar" ) );
	public static final Integer MENU_INDEX_NO_CONTACTAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.no.contactar" ) );
	public static final Integer MENU_INDEX_RETENER = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.retener" ) );
	public static final Integer MENU_INDEX_DESRETENER = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.desretener" ) );
	public static final Integer MENU_INDEX_ENVIAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.enviar" ) );
	public static final Integer MENU_INDEX_NOENVIAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.noenviar" ) );
	public static final Integer MENU_INDEX_EFAX = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.efax" ) );
	public static final Integer MENU_INDEX_AUTORIZACION = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.autorizacion" ) );
	public static final Integer MENU_INDEX_SOBRE = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.sobre" ) );
	public static final Integer MENU_INDEX_DATOS_FACTURA = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.datosfactura" ) );
	public static final Integer MENU_INDEX_DESVINCULAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.desvincular" ) );
	public static final Integer MENU_INDEX_CREAR_GRUPO = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.crear.grupo" ) );
	public static final Integer MENU_INDEX_AGREGAR_GRUPO = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.agregar.grupo" ) );
	public static final Integer MENU_INDEX_AGREGAR_RX = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.agregar.rx" ) );
	public static final Integer MENU_INDEX_NUEVA_ORDEN = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.nueva.orden" ) );
	public static final Integer MENU_INDEX_ENTREGAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.entregar" ) );
	public static final Integer MENU_INDEX_DESENTREGAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.desentregar" ) );
	public static final Integer MENU_INDEX_IMPRIMIR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.imprimir.os" ) );
	public static final Integer MENU_INDEX_BODEGA = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.bodega" ) );
	public static final Integer MENU_INDEX_EXTERNO_ENVIAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.externo.enviar" ) );
	public static final Integer MENU_INDEX_EXTERNO_ELIMINAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.externo.eliminar" ) );
	public static final Integer MENU_INDEX_EXTERNO_ENTREGAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.externo.entregar" ) );
	public static final Integer MENU_INDEX_FORMACONTACTO_MODIFICAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.formacontacto.modificar" ) );
	public static final Integer MENU_INDEX_GARANTIA_NUEVA = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.nueva" ) );
	public static final Integer MENU_INDEX_GARANTIA_ENTREGAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.entregar" ) );
	public static final Integer MENU_INDEX_GARANTIA_DESENTREGAR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.desentregar" ) );
	public static final Integer MENU_INDEX_GARANTIA_IMPRIMIR = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.imprimir" ) );
	public static final Integer MENU_INDEX_GARANTIA_BODEGA = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.bodega" ) );
	public static final Integer MENU_INDEX_GARANTIA_REPOSICION = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.index.garantia.reposicion" ) );

	public static final Integer MENU_TOTAL = Integer.valueOf( ApplicationPropertyHelper.getProperty( "menu.total" ) );
	public static final Integer MENU_SOBRES_TOTAL = Integer.valueOf( SobresPropertyHelper.getProperty( "sobres.menu.popup.total" ) );
	public static final Integer MENU_SOBRES_INDEX_NUEVO = Integer.valueOf( SobresPropertyHelper.getProperty( "sobres.menu.popup.index.nuevo" ) );
	public static final Integer MENU_SOBRES_INDEX_ELIMINAR = Integer.valueOf( SobresPropertyHelper.getProperty( "sobres.menu.popup.index.eliminar" ) );
	public static final Integer DEFAULT_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "default.tab.position" ) );
	public static final Integer CONTACTO_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "contacto.tab.position" ) );
	public static final Integer CONSULTA_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "consulta.tab.position" ) );
	public static final Integer RECEPCION_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "recepcion.tab.position" ) );
	public static final Integer ENVIOS_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "envios.tab.position" ) );
	public static final Integer ORDENSERVICIO_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "ordenservicio.tab.position" ) );
	public static final Integer GARANTIAS_TAB_POSITION = Integer.valueOf( TrabajosPropertyHelper.getProperty( "garantias.tab.position" ) );
	public static final String ITEM_SELECTED_ID_VIAJE = "currentIdViaje";
	public static final String ITEM_SELECTED_JB = "currentSelectedJb";
	public static final String ITEM_SELECTED_CLIENTE = "currentCliente";
	public static final String ITEM_NEW_ORDEN_SERVICIO = "newOrdenServicio";
	public static final String ENTREGAR = TrabajosPropertyHelper.getProperty( "recepcion.entregar" );
	public static String TRABAJO_PENDIENTE_AUTORIZAR = TrabajosPropertyHelper.getProperty( "obs.trabajo.pendiente.autorizar" );
	public static String OBS_VIAJE = TrabajosPropertyHelper.getProperty( "obs.viaje" );
	public static String OBS_RX_SOBRE = TrabajosPropertyHelper.getProperty( "obs.rx.sobre" );
	public static String EMPRESA_VAL = TrabajosPropertyHelper.getProperty( "empresa.val" );
	public static String EMPLEADO_VAL = TrabajosPropertyHelper.getProperty( "empleado.val" );
	public static String FACTURA_VAL = TrabajosPropertyHelper.getProperty( "factura.val" );
	public static String PARIENTE_VAL = TrabajosPropertyHelper.getProperty( "pariente.val" );
	public static String NOMBRE_PTE_VAL = TrabajosPropertyHelper.getProperty( "nombre.pte.val" );
	public static String ARTICULO_VAL = TrabajosPropertyHelper.getProperty( "articulo.val" );
	public static String TIPO_COMPRA_VAL = TrabajosPropertyHelper.getProperty( "tipo.compra.val" );
	public static String IMPORTE_VAL = TrabajosPropertyHelper.getProperty( "importe.val" );
	public static String DESCUENTO_VAL = TrabajosPropertyHelper.getProperty( "descuento.val" );
	public static String QUINCENAS_VAL = TrabajosPropertyHelper.getProperty( "quincenas.val" );
	public static String SUCURSAL_VAL = TrabajosPropertyHelper.getProperty( "sucursal.val" );
	public static String CONVENIO_VAL = TrabajosPropertyHelper.getProperty( "convenio.val" );
	public static String ID_SUCURSAL_VAL = TrabajosPropertyHelper.getProperty( "id.sucursal.val" );
	public static String ID_ARTICULO_VAL = TrabajosPropertyHelper.getProperty( "id.articulo.val" );
	public static String ID_ACUSE_VAL = TrabajosPropertyHelper.getProperty( "id.acuse.val" );
	public static String ID_COLOR_VAL = TrabajosPropertyHelper.getProperty( "id.color.val" );
	public static String RX_VAL = TrabajosPropertyHelper.getProperty( "rx.val" );
	public static String FECHA_VAL = TrabajosPropertyHelper.getProperty( "fecha.val" );
	public static String HORA_VAL = TrabajosPropertyHelper.getProperty( "hora.val" );
	public static String ENVIO_VAL = TrabajosPropertyHelper.getProperty( "envio.val" );
	public static String RX_DOS_PUNTOS = TrabajosPropertyHelper.getProperty( "trabajos.label.rx.dos.puntos" );
    public static String REIMPRIMIR_PACKING_DOS_PUNTOS = TrabajosPropertyHelper.getProperty( "trabajos.label.rpacking.dos.puntos" );
	public static String GRUPO_DOS_PUNTOS = TrabajosPropertyHelper.getProperty( "trabajos.label.grupo.dos.puntos" );
	public static String DEVOLUCIONES_ESTADO_PENDIENTE = TrabajosPropertyHelper.getProperty( "devoluciones.estado.pendiente" );
	public static String DEVOLUCIONES_ESTADO_ENVIADO = TrabajosPropertyHelper.getProperty( "devoluciones.estado.enviado" );
	public static String DEVOLUCIONES_TIPO_DA = TrabajosPropertyHelper.getProperty( "devoluciones.tipo.da" );
	public static String ARTICULOS_ID_GENERICO_ARMAZON = TrabajosPropertyHelper.getProperty( "articulos.id.generico.armazon" );
	public static String ARTICULOS_ID_GENERICO_LENTE = TrabajosPropertyHelper.getProperty( "articulos.id.generico.lente" );
	public static String CLIENTE_TIPO_NUEVO = TrabajosPropertyHelper.getProperty( "cliente.tipo.nuevo" );
	public static String JBNOTA_TIPO_SERVICIO = TrabajosPropertyHelper.getProperty( "jb.nota.tipo.servicio" );
	public static String LETRA_S = TrabajosPropertyHelper.getProperty( "letra.s" );
	public static String SKU_VAL = TrabajosPropertyHelper.getProperty( "sku.val" );

}
