package mx.com.lux.control.trabajos.data.vo;
// default package
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * CodigoxxId generated by hbm2java
 */
public class CodigoId implements java.io.Serializable {

	private String idEstado;
	private String idLocalidad;
	private String codigo;
	private String usuario;

	public CodigoId() {
	}

	public CodigoId( String idEstado, String idLocalidad, String codigo, String usuario ) {
		this.idEstado = idEstado;
		this.idLocalidad = idLocalidad;
		this.codigo = codigo;
		this.usuario = usuario;
	}

	public String getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado( String idEstado ) {
		this.idEstado = idEstado;
	}

	public String getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad( String idLocalidad ) {
		this.idLocalidad = idLocalidad;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo( String codigo ) {
		this.codigo = codigo;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario( String usuario ) {
		this.usuario = usuario;
	}
}
