package mx.com.lux.control.trabajos.data.vo;
// default package
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DoctoInv generated by hbm2java
 */
public class DoctoInv implements java.io.Serializable {

	private String idDocto;
	private String idTipoDocto;
	private Date fecha;
	private String usuario;
	private String referencia;
	private char idSync;
	private String idMod;
	private Date fechaMod;
	private int idSucursal;
	private String notas;
	private String cantidad;
	private String estado;

	public DoctoInv() {
	}

	public DoctoInv( String idDocto, String idTipoDocto, Date fecha, char idSync, String idMod, Date fechaMod, int idSucursal ) {
		this.idDocto = idDocto;
		this.idTipoDocto = idTipoDocto;
		this.fecha = fecha;
		this.idSync = idSync;
		this.idMod = idMod;
		this.fechaMod = fechaMod;
		this.idSucursal = idSucursal;
	}

	public DoctoInv( String idDocto, String idTipoDocto, Date fecha, String usuario, String referencia, char idSync, String idMod, Date fechaMod, int idSucursal, String notas, String cantidad, String estado ) {
		this.idDocto = idDocto;
		this.idTipoDocto = idTipoDocto;
		this.fecha = fecha;
		this.usuario = usuario;
		this.referencia = referencia;
		this.idSync = idSync;
		this.idMod = idMod;
		this.fechaMod = fechaMod;
		this.idSucursal = idSucursal;
		this.notas = notas;
		this.cantidad = cantidad;
		this.estado = estado;
	}

	public String getIdDocto() {
		return this.idDocto;
	}

	public void setIdDocto( String idDocto ) {
		this.idDocto = idDocto;
	}

	public String getIdTipoDocto() {
		return this.idTipoDocto;
	}

	public void setIdTipoDocto( String idTipoDocto ) {
		this.idTipoDocto = idTipoDocto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha( Date fecha ) {
		this.fecha = fecha;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario( String usuario ) {
		this.usuario = usuario;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia( String referencia ) {
		this.referencia = referencia;
	}

	public char getIdSync() {
		return this.idSync;
	}

	public void setIdSync( char idSync ) {
		this.idSync = idSync;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public int getIdSucursal() {
		return this.idSucursal;
	}

	public void setIdSucursal( int idSucursal ) {
		this.idSucursal = idSucursal;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas( String notas ) {
		this.notas = notas;
	}

	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad( String cantidad ) {
		this.cantidad = cantidad;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado( String estado ) {
		this.estado = estado;
	}

}
