package mx.com.lux.control.trabajos.data.vo;

import java.util.Date;
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * Dominios generated by Saúl Fragoso
 */
public class Dominios implements java.io.Serializable {

	private int idDominio;
	private String nombre;
	private Date fechaMod;

	public Dominios() {
	}

	public Dominios( int idDominio, String nombre, Date fechaMod ) {
		this.idDominio = idDominio;
		this.nombre = nombre;
		this.fechaMod = fechaMod;
	}

	public int getIdDominio() {
		return this.idDominio;
	}

	public void setIdDominio( int idDominio ) {
		this.idDominio = idDominio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre( String nombre ) {
		this.nombre = nombre;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}
}
