package mx.com.lux.control.trabajos.data.vo;

import java.util.Date;

/**
 * DominiosId generated by Saúl Fragoso
 */
public class DominiosId implements java.io.Serializable {

	private int idDominio;
	private String nombre;
	private Date fechaMod;

	public DominiosId() {
	}

	public DominiosId( int idDominio ) {
		this.idDominio = idDominio;
	}

	public DominiosId( int idDominio, String nombre, Date fechaMod ) {
		this.idDominio = idDominio;
		this.nombre = nombre;
		this.fechaMod = fechaMod;
	}

	public int getIdDominio() {
		return this.idDominio;
	}

	public void setIdDominio( int idDominio ) {
		this.idDominio = idDominio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre( String nombre ) {
		this.nombre = nombre;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof DominiosId ) )
			return false;
		DominiosId castOther = (DominiosId) other;

		return ( this.getIdDominio() == castOther.getIdDominio() ) && ( ( this.getNombre() == castOther.getNombre() ) || ( this.getNombre() != null && castOther.getNombre() != null && this.getNombre().equals( castOther.getNombre() ) ) ) && ( ( this.getFechaMod() == castOther.getFechaMod() ) || ( this.getFechaMod() != null && castOther.getFechaMod() != null && this.getFechaMod().equals( castOther.getFechaMod() ) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDominio();
		result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
		result = 37 * result + ( getFechaMod() == null ? 0 : this.getFechaMod().hashCode() );
		return result;
	}

}
