package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmpresaFicha generated by hbm2java
 */
public class EmpresaFicha implements java.io.Serializable {

	private String idEmpresa;
	private String descripcion;

	public EmpresaFicha() {
	}

	public EmpresaFicha( String idEmpresa, String descripcion ) {
		this.idEmpresa = idEmpresa;
		this.descripcion = descripcion;
	}

	public String getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa( String idEmpresa ) {
		this.idEmpresa = idEmpresa;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion( String descripcion ) {
		this.descripcion = descripcion;
	}

}
