package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmpresaFichaId generated by hbm2java
 */
public class EmpresaFichaId implements java.io.Serializable {

	private String idEmpresa;
	private String descripcion;

	public EmpresaFichaId() {
	}

	public EmpresaFichaId( String idEmpresa, String descripcion ) {
		this.idEmpresa = idEmpresa;
		this.descripcion = descripcion;
	}

	public String getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa( String idEmpresa ) {
		this.idEmpresa = idEmpresa;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion( String descripcion ) {
		this.descripcion = descripcion;
	}

	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof EmpresaFichaId ) )
			return false;
		EmpresaFichaId castOther = (EmpresaFichaId) other;

		return ( ( this.getIdEmpresa() == castOther.getIdEmpresa() ) || ( this.getIdEmpresa() != null && castOther.getIdEmpresa() != null && this.getIdEmpresa().equals( castOther.getIdEmpresa() ) ) ) && ( ( this.getDescripcion() == castOther.getDescripcion() ) || ( this.getDescripcion() != null && castOther.getDescripcion() != null && this.getDescripcion().equals( castOther.getDescripcion() ) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + ( getIdEmpresa() == null ? 0 : this.getIdEmpresa().hashCode() );
		result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
		return result;
	}

}
