package mx.com.lux.control.trabajos.data.vo;
// default package
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InstitucionIc generated by hbm2java
 */
public class InstitucionIc implements java.io.Serializable {

	private String idConvenio;
	private String inicialesIc;
	private String razonSocial;
	private Character tipoConvenio;
	private String idConvenioPrinci;
	private Double porcentajeAlTope;
	private String memoCondiciones;
	private Character estatusConvenio;
	private Boolean aceptarVales;
	private boolean FAcumularTope;
	private boolean FRestricLente;
	private char idSync;
	private Date fechaMod;
	private String idMod;
	private int idSucursal;
	private Boolean mejorPrecio;
	private String topeAnt;

	public InstitucionIc() {
	}

	public InstitucionIc( String idConvenio, boolean FAcumularTope, boolean FRestricLente, char idSync, Date fechaMod, String idMod, int idSucursal ) {
		this.idConvenio = idConvenio;
		this.FAcumularTope = FAcumularTope;
		this.FRestricLente = FRestricLente;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.idSucursal = idSucursal;
	}

	public InstitucionIc( String idConvenio, String inicialesIc, String razonSocial, Character tipoConvenio, String idConvenioPrinci, Double porcentajeAlTope, String memoCondiciones, Character estatusConvenio, Boolean aceptarVales, boolean FAcumularTope, boolean FRestricLente, char idSync, Date fechaMod, String idMod, int idSucursal, Boolean mejorPrecio, String topeAnt ) {
		this.idConvenio = idConvenio;
		this.inicialesIc = inicialesIc;
		this.razonSocial = razonSocial;
		this.tipoConvenio = tipoConvenio;
		this.idConvenioPrinci = idConvenioPrinci;
		this.porcentajeAlTope = porcentajeAlTope;
		this.memoCondiciones = memoCondiciones;
		this.estatusConvenio = estatusConvenio;
		this.aceptarVales = aceptarVales;
		this.FAcumularTope = FAcumularTope;
		this.FRestricLente = FRestricLente;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.idSucursal = idSucursal;
		this.mejorPrecio = mejorPrecio;
		this.topeAnt = topeAnt;
	}

	public String getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio( String idConvenio ) {
		this.idConvenio = idConvenio;
	}

	public String getInicialesIc() {
		return this.inicialesIc;
	}

	public void setInicialesIc( String inicialesIc ) {
		this.inicialesIc = inicialesIc;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial( String razonSocial ) {
		this.razonSocial = razonSocial;
	}

	public Character getTipoConvenio() {
		return this.tipoConvenio;
	}

	public void setTipoConvenio( Character tipoConvenio ) {
		this.tipoConvenio = tipoConvenio;
	}

	public String getIdConvenioPrinci() {
		return this.idConvenioPrinci;
	}

	public void setIdConvenioPrinci( String idConvenioPrinci ) {
		this.idConvenioPrinci = idConvenioPrinci;
	}

	public Double getPorcentajeAlTope() {
		return this.porcentajeAlTope;
	}

	public void setPorcentajeAlTope( Double porcentajeAlTope ) {
		this.porcentajeAlTope = porcentajeAlTope;
	}

	public String getMemoCondiciones() {
		return this.memoCondiciones;
	}

	public void setMemoCondiciones( String memoCondiciones ) {
		this.memoCondiciones = memoCondiciones;
	}

	public Character getEstatusConvenio() {
		return this.estatusConvenio;
	}

	public void setEstatusConvenio( Character estatusConvenio ) {
		this.estatusConvenio = estatusConvenio;
	}

	public Boolean getAceptarVales() {
		return this.aceptarVales;
	}

	public void setAceptarVales( Boolean aceptarVales ) {
		this.aceptarVales = aceptarVales;
	}

	public boolean isFAcumularTope() {
		return this.FAcumularTope;
	}

	public void setFAcumularTope( boolean FAcumularTope ) {
		this.FAcumularTope = FAcumularTope;
	}

	public boolean isFRestricLente() {
		return this.FRestricLente;
	}

	public void setFRestricLente( boolean FRestricLente ) {
		this.FRestricLente = FRestricLente;
	}

	public char getIdSync() {
		return this.idSync;
	}

	public void setIdSync( char idSync ) {
		this.idSync = idSync;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public int getIdSucursal() {
		return this.idSucursal;
	}

	public void setIdSucursal( int idSucursal ) {
		this.idSucursal = idSucursal;
	}

	public Boolean getMejorPrecio() {
		return this.mejorPrecio;
	}

	public void setMejorPrecio( Boolean mejorPrecio ) {
		this.mejorPrecio = mejorPrecio;
	}

	public String getTopeAnt() {
		return this.topeAnt;
	}

	public void setTopeAnt( String topeAnt ) {
		this.topeAnt = topeAnt;
	}

}
