package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

/**
 * JbDevId generated by hbm2java
 */
public class JbDevId implements java.io.Serializable {

	private int idDev;
	private String factura;
	private String sucursal;
	private String apartado;
	private String idViaje;
	private String documento;
	private String arm;
	private String col;
	private Date fechaEnvio;
	private Timestamp fecha;
	private String idMod;
	private boolean rx;

	public JbDevId() {
	}

	public JbDevId( int idDev, Timestamp fecha, boolean rx ) {
		this.idDev = idDev;
		this.fecha = fecha;
		this.rx = rx;
	}

	public JbDevId( int idDev, String factura, String sucursal, String apartado, String idViaje, String documento, String arm, String col, Date fechaEnvio, Timestamp fecha, String idMod, boolean rx ) {
		this.idDev = idDev;
		this.factura = factura;
		this.sucursal = sucursal;
		this.apartado = apartado;
		this.idViaje = idViaje;
		this.documento = documento;
		this.arm = arm;
		this.col = col;
		this.fechaEnvio = fechaEnvio;
		this.fecha = fecha;
		this.idMod = idMod;
		this.rx = rx;
	}

	public int getIdDev() {
		return this.idDev;
	}

	public void setIdDev( int idDev ) {
		this.idDev = idDev;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura( String factura ) {
		this.factura = factura;
	}

	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal( String sucursal ) {
		this.sucursal = sucursal;
	}

	public String getApartado() {
		return this.apartado;
	}

	public void setApartado( String apartado ) {
		this.apartado = apartado;
	}

	public String getIdViaje() {
		return this.idViaje;
	}

	public void setIdViaje( String idViaje ) {
		this.idViaje = idViaje;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento( String documento ) {
		this.documento = documento;
	}

	public String getArm() {
		return this.arm;
	}

	public void setArm( String arm ) {
		this.arm = arm;
	}

	public String getCol() {
		return this.col;
	}

	public void setCol( String col ) {
		this.col = col;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio( Date fechaEnvio ) {
		this.fechaEnvio = fechaEnvio;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha( Timestamp fecha ) {
		this.fecha = fecha;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public boolean isRx() {
		return this.rx;
	}

	public void setRx( boolean rx ) {
		this.rx = rx;
	}

	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof JbDevId ) )
			return false;
		JbDevId castOther = (JbDevId) other;

		return ( this.getIdDev() == castOther.getIdDev() ) && ( ( this.getFactura() == castOther.getFactura() ) || ( this.getFactura() != null && castOther.getFactura() != null && this.getFactura().equals( castOther.getFactura() ) ) ) && ( ( this.getSucursal() == castOther.getSucursal() ) || ( this.getSucursal() != null && castOther.getSucursal() != null && this.getSucursal().equals( castOther.getSucursal() ) ) ) && ( ( this.getApartado() == castOther.getApartado() ) || ( this.getApartado() != null && castOther.getApartado() != null && this.getApartado().equals( castOther.getApartado() ) ) ) && ( ( this.getIdViaje() == castOther.getIdViaje() ) || ( this.getIdViaje() != null && castOther.getIdViaje() != null && this.getIdViaje().equals( castOther.getIdViaje() ) ) ) && ( ( this.getDocumento() == castOther.getDocumento() ) || ( this.getDocumento() != null && castOther.getDocumento() != null && this.getDocumento().equals( castOther.getDocumento() ) ) ) && ( ( this.getArm() == castOther.getArm() ) || ( this.getArm() != null && castOther.getArm() != null && this.getArm().equals( castOther.getArm() ) ) ) && ( ( this.getCol() == castOther.getCol() ) || ( this.getCol() != null && castOther.getCol() != null && this.getCol().equals( castOther.getCol() ) ) ) && ( ( this.getFechaEnvio() == castOther.getFechaEnvio() ) || ( this.getFechaEnvio() != null && castOther.getFechaEnvio() != null && this.getFechaEnvio().equals( castOther.getFechaEnvio() ) ) ) && ( ( this.getFecha() == castOther.getFecha() ) || ( this.getFecha() != null && castOther.getFecha() != null && this.getFecha().equals( castOther.getFecha() ) ) ) && ( ( this.getIdMod() == castOther.getIdMod() ) || ( this.getIdMod() != null && castOther.getIdMod() != null && this.getIdMod().equals( castOther.getIdMod() ) ) ) && ( this.isRx() == castOther.isRx() );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDev();
		result = 37 * result + ( getFactura() == null ? 0 : this.getFactura().hashCode() );
		result = 37 * result + ( getSucursal() == null ? 0 : this.getSucursal().hashCode() );
		result = 37 * result + ( getApartado() == null ? 0 : this.getApartado().hashCode() );
		result = 37 * result + ( getIdViaje() == null ? 0 : this.getIdViaje().hashCode() );
		result = 37 * result + ( getDocumento() == null ? 0 : this.getDocumento().hashCode() );
		result = 37 * result + ( getArm() == null ? 0 : this.getArm().hashCode() );
		result = 37 * result + ( getCol() == null ? 0 : this.getCol().hashCode() );
		result = 37 * result + ( getFechaEnvio() == null ? 0 : this.getFechaEnvio().hashCode() );
		result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
		result = 37 * result + ( getIdMod() == null ? 0 : this.getIdMod().hashCode() );
		result = 37 * result + ( this.isRx() ? 1 : 0 );
		return result;
	}

}
