package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * JbExterno generated by hbm2java
 */
public class JbExterno implements Serializable {

	private static final long serialVersionUID = 2893695057705082671L;

	private String factura;
	private String origen;
	private Integer idCliente;
	private String lente;
	private String armazon;
	private String material;
	private String forma;
	private Date fechaEntrega;
	private Date fechaPromesa;
	private Date fechaFactura;

	public JbExterno() {
	}

	public JbExterno( String factura ) {
		this.factura = factura;
	}

	public JbExterno( String factura, String origen, Integer idCliente, String lente, String armazon, String material, String forma, Date fechaEntrega, Date fechaPromesa, Date fechaFactura ) {
		this.factura = factura;
		this.origen = origen;
		this.idCliente = idCliente;
		this.lente = lente;
		this.armazon = armazon;
		this.material = material;
		this.forma = forma;
		this.fechaEntrega = fechaEntrega;
		this.fechaPromesa = fechaPromesa;
		this.fechaFactura = fechaFactura;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura( String factura ) {
		this.factura = factura;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen( String origen ) {
		this.origen = origen;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente( Integer idCliente ) {
		this.idCliente = idCliente;
	}

	public String getLente() {
		return this.lente;
	}

	public void setLente( String lente ) {
		this.lente = lente;
	}

	public String getArmazon() {
		return this.armazon;
	}

	public void setArmazon( String armazon ) {
		this.armazon = armazon;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial( String material ) {
		this.material = material;
	}

	public String getForma() {
		return this.forma;
	}

	public void setForma( String forma ) {
		this.forma = forma;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega( Date fechaEntrega ) {
		this.fechaEntrega = fechaEntrega;
	}

	public Date getFechaPromesa() {
		return this.fechaPromesa;
	}

	public void setFechaPromesa( Date fechaPromesa ) {
		this.fechaPromesa = fechaPromesa;
	}

	public Date getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura( Date fechaFactura ) {
		this.fechaFactura = fechaFactura;
	}

}
