package mx.com.lux.control.trabajos.data.vo;

import java.sql.Timestamp;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * JbGrupoDetalle generated by hbm2java
 */
public class JbGrupoDetalle implements java.io.Serializable {

	private JbGrupoDetalleId id;
	private Jb jb;
	private Timestamp fecha;
	private String idMod;


	public JbGrupoDetalle() {
	}

	public JbGrupoDetalle( JbGrupoDetalleId id, Timestamp fecha, String idMod ) {
		super();
		this.id = id;
		this.fecha = fecha;
		this.idMod = idMod;
	}


	public JbGrupoDetalle( JbGrupoDetalleId id, Jb jb, Timestamp fecha, String idMod ) {
		super();
		this.id = id;
		this.jb = jb;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	/**
	 * @return the id
	 */
	public JbGrupoDetalleId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId( JbGrupoDetalleId id ) {
		this.id = id;
	}

	/**
	 * @return the jb
	 */
	public Jb getJb() {
		return jb;
	}

	/**
	 * @param jb the jb to set
	 */
	public void setJb( Jb jb ) {
		this.jb = jb;
	}

	/**
	 * @return the fecha
	 */
	public Timestamp getFecha() {
		return fecha;
	}

	/**
	 * @param fecha the fecha to set
	 */
	public void setFecha( Timestamp fecha ) {
		this.fecha = fecha;
	}

	/**
	 * @return the idMod
	 */
	public String getIdMod() {
		return idMod;
	}

	/**
	 * @param idMod the idMod to set
	 */
	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}


}
