package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1


/**
 * JbGrupoDetalleId generated by hbm2java
 */
public class JbGrupoDetalleId implements java.io.Serializable {

	private Integer idGrupo;
	private String rx;


	public JbGrupoDetalleId() {
	}


	public JbGrupoDetalleId( Integer idGrupo, String rx ) {
		this.idGrupo = idGrupo;
		this.rx = rx;
	}

	public Integer getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo( Integer idGrupo ) {
		this.idGrupo = idGrupo;
	}

	public String getRx() {
		return this.rx;
	}

	public void setRx( String rx ) {
		this.rx = rx;
	}


	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof JbGrupoDetalleId ) )
			return false;
		JbGrupoDetalleId castOther = (JbGrupoDetalleId) other;

		return ( ( this.getIdGrupo() == castOther.getIdGrupo() ) || ( this.getIdGrupo() != null && castOther.getIdGrupo() != null && this.getIdGrupo().equals( castOther.getIdGrupo() ) ) ) && ( ( this.getRx() == castOther.getRx() ) || ( this.getRx() != null && castOther.getRx() != null && this.getRx().equals( castOther.getRx() ) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + ( getIdGrupo() == null ? 0 : this.getIdGrupo().hashCode() );
		result = 37 * result + ( getRx() == null ? 0 : this.getRx().hashCode() );
		return result;
	}

}
