package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

/**
 * JbRotoId generated by hbm2java
 */
public class JbRotoId implements java.io.Serializable {

	private int idRoto;
	private String rx;
	private String tipo;
	private String material;
	private String causa;
	private String emp;
	private int numRoto;
	private boolean alta;
	private Date fechaProm;
	private Boolean llamada;
	private Timestamp fecha;
	private String idMod;

	public JbRotoId() {
	}

	public JbRotoId( int idRoto, int numRoto, boolean alta, Timestamp fecha, String idMod ) {
		this.idRoto = idRoto;
		this.numRoto = numRoto;
		this.alta = alta;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	public JbRotoId( int idRoto, String rx, String tipo, String material, String causa, String emp, int numRoto, boolean alta, Date fechaProm, Boolean llamada, Timestamp fecha, String idMod ) {
		this.idRoto = idRoto;
		this.rx = rx;
		this.tipo = tipo;
		this.material = material;
		this.causa = causa;
		this.emp = emp;
		this.numRoto = numRoto;
		this.alta = alta;
		this.fechaProm = fechaProm;
		this.llamada = llamada;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	public int getIdRoto() {
		return this.idRoto;
	}

	public void setIdRoto( int idRoto ) {
		this.idRoto = idRoto;
	}

	public String getRx() {
		return this.rx;
	}

	public void setRx( String rx ) {
		this.rx = rx;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo( String tipo ) {
		this.tipo = tipo;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial( String material ) {
		this.material = material;
	}

	public String getCausa() {
		return this.causa;
	}

	public void setCausa( String causa ) {
		this.causa = causa;
	}

	public String getEmp() {
		return this.emp;
	}

	public void setEmp( String emp ) {
		this.emp = emp;
	}

	public int getNumRoto() {
		return this.numRoto;
	}

	public void setNumRoto( int numRoto ) {
		this.numRoto = numRoto;
	}

	public boolean isAlta() {
		return this.alta;
	}

	public void setAlta( boolean alta ) {
		this.alta = alta;
	}

	public Date getFechaProm() {
		return this.fechaProm;
	}

	public void setFechaProm( Date fechaProm ) {
		this.fechaProm = fechaProm;
	}

	public Boolean getLlamada() {
		return this.llamada;
	}

	public void setLlamada( Boolean llamada ) {
		this.llamada = llamada;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha( Timestamp fecha ) {
		this.fecha = fecha;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof JbRotoId ) )
			return false;
		JbRotoId castOther = (JbRotoId) other;

		return ( this.getIdRoto() == castOther.getIdRoto() ) && ( ( this.getRx() == castOther.getRx() ) || ( this.getRx() != null && castOther.getRx() != null && this.getRx().equals( castOther.getRx() ) ) ) && ( ( this.getTipo() == castOther.getTipo() ) || ( this.getTipo() != null && castOther.getTipo() != null && this.getTipo().equals( castOther.getTipo() ) ) ) && ( ( this.getMaterial() == castOther.getMaterial() ) || ( this.getMaterial() != null && castOther.getMaterial() != null && this.getMaterial().equals( castOther.getMaterial() ) ) ) && ( ( this.getCausa() == castOther.getCausa() ) || ( this.getCausa() != null && castOther.getCausa() != null && this.getCausa().equals( castOther.getCausa() ) ) ) && ( ( this.getEmp() == castOther.getEmp() ) || ( this.getEmp() != null && castOther.getEmp() != null && this.getEmp().equals( castOther.getEmp() ) ) ) && ( this.getNumRoto() == castOther.getNumRoto() ) && ( this.isAlta() == castOther.isAlta() ) && ( ( this.getFechaProm() == castOther.getFechaProm() ) || ( this.getFechaProm() != null && castOther.getFechaProm() != null && this.getFechaProm().equals( castOther.getFechaProm() ) ) ) && ( ( this.getLlamada() == castOther.getLlamada() ) || ( this.getLlamada() != null && castOther.getLlamada() != null && this.getLlamada().equals( castOther.getLlamada() ) ) ) && ( ( this.getFecha() == castOther.getFecha() ) || ( this.getFecha() != null && castOther.getFecha() != null && this.getFecha().equals( castOther.getFecha() ) ) ) && ( ( this.getIdMod() == castOther.getIdMod() ) || ( this.getIdMod() != null && castOther.getIdMod() != null && this.getIdMod().equals( castOther.getIdMod() ) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRoto();
		result = 37 * result + ( getRx() == null ? 0 : this.getRx().hashCode() );
		result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
		result = 37 * result + ( getMaterial() == null ? 0 : this.getMaterial().hashCode() );
		result = 37 * result + ( getCausa() == null ? 0 : this.getCausa().hashCode() );
		result = 37 * result + ( getEmp() == null ? 0 : this.getEmp().hashCode() );
		result = 37 * result + this.getNumRoto();
		result = 37 * result + ( this.isAlta() ? 1 : 0 );
		result = 37 * result + ( getFechaProm() == null ? 0 : this.getFechaProm().hashCode() );
		result = 37 * result + ( getLlamada() == null ? 0 : this.getLlamada().hashCode() );
		result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
		result = 37 * result + ( getIdMod() == null ? 0 : this.getIdMod().hashCode() );
		return result;
	}

}
