package mx.com.lux.control.trabajos.data.vo;

import java.sql.Timestamp;
import java.util.Date;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * JbRoto generated by hbm2java
 */
public class JbRoto implements java.io.Serializable {

	private static final long serialVersionUID = -7037007897335012771L;

	private int idRoto;
	private String rx;
	private String tipo;
	private String material;
	private String causa;
	private String emp;
	private int numRoto;
	private boolean alta;
	private Date fechaProm;
	private Boolean llamada;
	private Timestamp fecha;
	private String idMod;

	public JbRoto() {
	}

	public JbRoto( int idRoto, int numRoto, boolean alta, Timestamp fecha, String idMod ) {
		this.idRoto = idRoto;
		this.numRoto = numRoto;
		this.alta = alta;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	public JbRoto( int idRoto, String rx, String tipo, String material, String causa, String emp, int numRoto, boolean alta, Date fechaProm, Boolean llamada, Timestamp fecha, String idMod ) {
		this.idRoto = idRoto;
		this.rx = rx;
		this.tipo = tipo;
		this.material = material;
		this.causa = causa;
		this.emp = emp;
		this.numRoto = numRoto;
		this.alta = alta;
		this.fechaProm = fechaProm;
		this.llamada = llamada;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	public int getIdRoto() {
		return idRoto;
	}

	public void setIdRoto( int idRoto ) {
		this.idRoto = idRoto;
	}

	public String getRx() {
		return this.rx;
	}

	public void setRx( String rx ) {
		this.rx = rx;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo( String tipo ) {
		this.tipo = tipo;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial( String material ) {
		this.material = material;
	}

	public String getCausa() {
		return this.causa;
	}

	public void setCausa( String causa ) {
		this.causa = causa;
	}

	public String getEmp() {
		return this.emp;
	}

	public void setEmp( String emp ) {
		this.emp = emp;
	}

	public int getNumRoto() {
		return this.numRoto;
	}

	public void setNumRoto( int numRoto ) {
		this.numRoto = numRoto;
	}

	public boolean isAlta() {
		return this.alta;
	}

	public void setAlta( boolean alta ) {
		this.alta = alta;
	}

	public Date getFechaProm() {
		return this.fechaProm;
	}

	public void setFechaProm( Date fechaProm ) {
		this.fechaProm = fechaProm;
	}

	public Boolean getLlamada() {
		return this.llamada;
	}

	public void setLlamada( Boolean llamada ) {
		this.llamada = llamada;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha( Timestamp fecha ) {
		this.fecha = fecha;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}
}
