package mx.com.lux.control.trabajos.data.vo;

import java.io.Serializable;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * JbServicio generated by hbm2java
 */
public class JbServicio implements Serializable {

	private static final long serialVersionUID = 5146001691205531678L;

    private Integer idServicio;
    private String servicio;

	public JbServicio() {
	}

	public JbServicio( String servicio ) {
		this.servicio = servicio;
	}

	public String getServicio() {
		return this.servicio;
	}

	public void setServicio( String servicio ) {
		this.servicio = servicio;
	}

    public Integer getIdServicio() {
        return idServicio;
    }

    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
}
