package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

/**
 * JbSobreId generated by hbm2java
 */
public class JbSobreId implements java.io.Serializable {

	private int idSobre;
	private String folioSobre;
	private String dest;
	private String emp;
	private String area;
	private String contenido;
	private String idViaje;
	private Date fechaEnvio;
	private Timestamp fecha;
	private String idMod;
	private String rx;

	public JbSobreId() {
	}

	public JbSobreId( int idSobre, Timestamp fecha, String idMod ) {
		this.idSobre = idSobre;
		this.fecha = fecha;
		this.idMod = idMod;
	}

	public JbSobreId( int idSobre, String folioSobre, String dest, String emp, String area, String contenido, String idViaje, Date fechaEnvio, Timestamp fecha, String idMod, String rx ) {
		this.idSobre = idSobre;
		this.folioSobre = folioSobre;
		this.dest = dest;
		this.emp = emp;
		this.area = area;
		this.contenido = contenido;
		this.idViaje = idViaje;
		this.fechaEnvio = fechaEnvio;
		this.fecha = fecha;
		this.idMod = idMod;
		this.rx = rx;
	}

	public int getIdSobre() {
		return this.idSobre;
	}

	public void setIdSobre( int idSobre ) {
		this.idSobre = idSobre;
	}

	public String getFolioSobre() {
		return this.folioSobre;
	}

	public void setFolioSobre( String folioSobre ) {
		this.folioSobre = folioSobre;
	}

	public String getDest() {
		return this.dest;
	}

	public void setDest( String dest ) {
		this.dest = dest;
	}

	public String getEmp() {
		return this.emp;
	}

	public void setEmp( String emp ) {
		this.emp = emp;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea( String area ) {
		this.area = area;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido( String contenido ) {
		this.contenido = contenido;
	}

	public String getIdViaje() {
		return this.idViaje;
	}

	public void setIdViaje( String idViaje ) {
		this.idViaje = idViaje;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio( Date fechaEnvio ) {
		this.fechaEnvio = fechaEnvio;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha( Timestamp fecha ) {
		this.fecha = fecha;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public String getRx() {
		return this.rx;
	}

	public void setRx( String rx ) {
		this.rx = rx;
	}

	public boolean equals( Object other ) {
		if ( ( this == other ) )
			return true;
		if ( ( other == null ) )
			return false;
		if ( !( other instanceof JbSobreId ) )
			return false;
		JbSobreId castOther = (JbSobreId) other;

		return ( this.getIdSobre() == castOther.getIdSobre() ) && ( ( this.getFolioSobre() == castOther.getFolioSobre() ) || ( this.getFolioSobre() != null && castOther.getFolioSobre() != null && this.getFolioSobre().equals( castOther.getFolioSobre() ) ) ) && ( ( this.getDest() == castOther.getDest() ) || ( this.getDest() != null && castOther.getDest() != null && this.getDest().equals( castOther.getDest() ) ) ) && ( ( this.getEmp() == castOther.getEmp() ) || ( this.getEmp() != null && castOther.getEmp() != null && this.getEmp().equals( castOther.getEmp() ) ) ) && ( ( this.getArea() == castOther.getArea() ) || ( this.getArea() != null && castOther.getArea() != null && this.getArea().equals( castOther.getArea() ) ) ) && ( ( this.getContenido() == castOther.getContenido() ) || ( this.getContenido() != null && castOther.getContenido() != null && this.getContenido().equals( castOther.getContenido() ) ) ) && ( ( this.getIdViaje() == castOther.getIdViaje() ) || ( this.getIdViaje() != null && castOther.getIdViaje() != null && this.getIdViaje().equals( castOther.getIdViaje() ) ) ) && ( ( this.getFechaEnvio() == castOther.getFechaEnvio() ) || ( this.getFechaEnvio() != null && castOther.getFechaEnvio() != null && this.getFechaEnvio().equals( castOther.getFechaEnvio() ) ) ) && ( ( this.getFecha() == castOther.getFecha() ) || ( this.getFecha() != null && castOther.getFecha() != null && this.getFecha().equals( castOther.getFecha() ) ) ) && ( ( this.getIdMod() == castOther.getIdMod() ) || ( this.getIdMod() != null && castOther.getIdMod() != null && this.getIdMod().equals( castOther.getIdMod() ) ) ) && ( ( this.getRx() == castOther.getRx() ) || ( this.getRx() != null && castOther.getRx() != null && this.getRx().equals( castOther.getRx() ) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSobre();
		result = 37 * result + ( getFolioSobre() == null ? 0 : this.getFolioSobre().hashCode() );
		result = 37 * result + ( getDest() == null ? 0 : this.getDest().hashCode() );
		result = 37 * result + ( getEmp() == null ? 0 : this.getEmp().hashCode() );
		result = 37 * result + ( getArea() == null ? 0 : this.getArea().hashCode() );
		result = 37 * result + ( getContenido() == null ? 0 : this.getContenido().hashCode() );
		result = 37 * result + ( getIdViaje() == null ? 0 : this.getIdViaje().hashCode() );
		result = 37 * result + ( getFechaEnvio() == null ? 0 : this.getFechaEnvio().hashCode() );
		result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
		result = 37 * result + ( getIdMod() == null ? 0 : this.getIdMod().hashCode() );
		result = 37 * result + ( getRx() == null ? 0 : this.getRx().hashCode() );
		return result;
	}

}
