package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JbViaje generated by hbm2java
 */
public class JbViaje implements java.io.Serializable {

	private JbViajeId id;
	private String folio;
    private Date hora;
	private Boolean abierto;
	private String emp;

	public JbViaje() {
	}

	public JbViaje( JbViajeId id, Date hora ) {
		this.id = id;
		this.hora = hora;
	}

	public JbViaje( JbViajeId id, String folio, Date hora, Boolean abierto, String emp ) {
		this.id = id;
		this.folio = folio;
		this.hora = hora;
		this.abierto = abierto;
		this.emp = emp;
	}

	public JbViajeId getId() {
		return this.id;
	}

	public void setId( JbViajeId id ) {
		this.id = id;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio( String folio ) {
		this.folio = folio;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora( Date hora ) {
		this.hora = hora;
	}

	public Boolean getAbierto() {
		return this.abierto;
	}

	public void setAbierto( Boolean abierto ) {
		this.abierto = abierto;
	}

	public String getEmp() {
		return this.emp;
	}

	public void setEmp( String emp ) {
		this.emp = emp;
	}

}
