package mx.com.lux.control.trabajos.data.vo;

import java.util.Date;
// default package
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * NotaFactura generated by hbm2java
 */
public class NotaFactura implements java.io.Serializable {

	private String idFiscal;
	private String rfc;
	private String ticket;
	private String idEmpleado;
	private String idFactura;
	private String factura;
	private String tipo;
	private String facturaOri;
	private String idCliente;
	private String razon;
	private String estatus;
	private String tipoFac;
	private String nombre;
	private String calle;
	private String noexterior;
	private String nointerior;
	private String colonia;
	private String localidad;
	private String referencia;
	private String municipio;
	private String estado;
	private String pais;
	private String codigopostal;
	private Date fechaImpresion;
	private Date fechaMod;
	private String importe;
	private String email;
	private String url;
	private String xml;
	private String rx;
	private String paciente;
	private String formaPago;
	private String metodoPago;
	private String observaciones;

	public NotaFactura() {
	}

	public NotaFactura( String idFiscal, String rfc, String ticket, String idEmpleado, String idFactura, String factura, String tipo, String facturaOri, String idCliente, String razon, String estatus, String tipoFac, String nombre, String calle, String noexterior, String nointerior, String colonia, String localidad, String referencia, String municipio, String estado, String pais, String codigopostal, Date fechaImpresion, Date fechaMod, String importe, String email, String url, String xml, String rx, String paciente, String formaPago, String metodoPago, String observaciones ) {
		this.idFiscal = idFiscal;
		this.rfc = rfc;
		this.ticket = ticket;
		this.idEmpleado = idEmpleado;
		this.idFactura = idFactura;
		this.factura = factura;
		this.tipo = tipo;
		this.facturaOri = facturaOri;
		this.idCliente = idCliente;
		this.razon = razon;
		this.estatus = estatus;
		this.tipoFac = tipoFac;
		this.nombre = nombre;
		this.calle = calle;
		this.noexterior = noexterior;
		this.nointerior = nointerior;
		this.colonia = colonia;
		this.localidad = localidad;
		this.referencia = referencia;
		this.municipio = municipio;
		this.estado = estado;
		this.pais = pais;
		this.codigopostal = codigopostal;
		this.fechaImpresion = fechaImpresion;
		this.fechaMod = fechaMod;
		this.importe = importe;
		this.email = email;
		this.url = url;
		this.xml = xml;
		this.rx = rx;
		this.paciente = paciente;
		this.formaPago = formaPago;
		this.metodoPago = metodoPago;
		this.observaciones = observaciones;
	}

	public String getIdFiscal() {
		return this.idFiscal;
	}

	public void setIdFiscal( String idFiscal ) {
		this.idFiscal = idFiscal;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc( String rfc ) {
		this.rfc = rfc;
	}

	public String getTicket() {
		return this.ticket;
	}

	public void setTicket( String ticket ) {
		this.ticket = ticket;
	}

	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado( String idEmpleado ) {
		this.idEmpleado = idEmpleado;
	}

	public String getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura( String idFactura ) {
		this.idFactura = idFactura;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura( String factura ) {
		this.factura = factura;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo( String tipo ) {
		this.tipo = tipo;
	}

	public String getFacturaOri() {
		return this.facturaOri;
	}

	public void setFacturaOri( String facturaOri ) {
		this.facturaOri = facturaOri;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente( String idCliente ) {
		this.idCliente = idCliente;
	}

	public String getRazon() {
		return this.razon;
	}

	public void setRazon( String razon ) {
		this.razon = razon;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus( String estatus ) {
		this.estatus = estatus;
	}

	public String getTipoFac() {
		return this.tipoFac;
	}

	public void setTipoFac( String tipoFac ) {
		this.tipoFac = tipoFac;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre( String nombre ) {
		this.nombre = nombre;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle( String calle ) {
		this.calle = calle;
	}

	public String getNoexterior() {
		return this.noexterior;
	}

	public void setNoexterior( String noexterior ) {
		this.noexterior = noexterior;
	}

	public String getNointerior() {
		return this.nointerior;
	}

	public void setNointerior( String nointerior ) {
		this.nointerior = nointerior;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia( String colonia ) {
		this.colonia = colonia;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad( String localidad ) {
		this.localidad = localidad;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia( String referencia ) {
		this.referencia = referencia;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio( String municipio ) {
		this.municipio = municipio;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado( String estado ) {
		this.estado = estado;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais( String pais ) {
		this.pais = pais;
	}

	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal( String codigopostal ) {
		this.codigopostal = codigopostal;
	}

	public Date getFechaImpresion() {
		return this.fechaImpresion;
	}

	public void setFechaImpresion( Date fechaImpresion ) {
		this.fechaImpresion = fechaImpresion;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public String getImporte() {
		return this.importe;
	}

	public void setImporte( String importe ) {
		this.importe = importe;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl( String url ) {
		this.url = url;
	}

	public String getXml() {
		return this.xml;
	}

	public void setXml( String xml ) {
		this.xml = xml;
	}

	public String getRx() {
		return this.rx;
	}

	public void setRx( String rx ) {
		this.rx = rx;
	}

	public String getPaciente() {
		return this.paciente;
	}

	public void setPaciente( String paciente ) {
		this.paciente = paciente;
	}

	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago( String formaPago ) {
		this.formaPago = formaPago;
	}

	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago( String metodoPago ) {
		this.metodoPago = metodoPago;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones( String observaciones ) {
		this.observaciones = observaciones;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ( ( calle == null ) ? 0 : calle.hashCode() );
		result = prime * result + ( ( codigopostal == null ) ? 0 : codigopostal.hashCode() );
		result = prime * result + ( ( colonia == null ) ? 0 : colonia.hashCode() );
		result = prime * result + ( ( email == null ) ? 0 : email.hashCode() );
		result = prime * result + ( ( estado == null ) ? 0 : estado.hashCode() );
		result = prime * result + ( ( estatus == null ) ? 0 : estatus.hashCode() );
		result = prime * result + ( ( factura == null ) ? 0 : factura.hashCode() );
		result = prime * result + ( ( facturaOri == null ) ? 0 : facturaOri.hashCode() );
		result = prime * result + ( ( fechaImpresion == null ) ? 0 : fechaImpresion.hashCode() );
		result = prime * result + ( ( fechaMod == null ) ? 0 : fechaMod.hashCode() );
		result = prime * result + ( ( formaPago == null ) ? 0 : formaPago.hashCode() );
		result = prime * result + ( ( idCliente == null ) ? 0 : idCliente.hashCode() );
		result = prime * result + ( ( idEmpleado == null ) ? 0 : idEmpleado.hashCode() );
		result = prime * result + ( ( idFactura == null ) ? 0 : idFactura.hashCode() );
		result = prime * result + ( ( idFiscal == null ) ? 0 : idFiscal.hashCode() );
		result = prime * result + ( ( importe == null ) ? 0 : importe.hashCode() );
		result = prime * result + ( ( localidad == null ) ? 0 : localidad.hashCode() );
		result = prime * result + ( ( metodoPago == null ) ? 0 : metodoPago.hashCode() );
		result = prime * result + ( ( municipio == null ) ? 0 : municipio.hashCode() );
		result = prime * result + ( ( noexterior == null ) ? 0 : noexterior.hashCode() );
		result = prime * result + ( ( nointerior == null ) ? 0 : nointerior.hashCode() );
		result = prime * result + ( ( nombre == null ) ? 0 : nombre.hashCode() );
		result = prime * result + ( ( observaciones == null ) ? 0 : observaciones.hashCode() );
		result = prime * result + ( ( paciente == null ) ? 0 : paciente.hashCode() );
		result = prime * result + ( ( pais == null ) ? 0 : pais.hashCode() );
		result = prime * result + ( ( razon == null ) ? 0 : razon.hashCode() );
		result = prime * result + ( ( referencia == null ) ? 0 : referencia.hashCode() );
		result = prime * result + ( ( rfc == null ) ? 0 : rfc.hashCode() );
		result = prime * result + ( ( rx == null ) ? 0 : rx.hashCode() );
		result = prime * result + ( ( ticket == null ) ? 0 : ticket.hashCode() );
		result = prime * result + ( ( tipo == null ) ? 0 : tipo.hashCode() );
		result = prime * result + ( ( tipoFac == null ) ? 0 : tipoFac.hashCode() );
		result = prime * result + ( ( url == null ) ? 0 : url.hashCode() );
		result = prime * result + ( ( xml == null ) ? 0 : xml.hashCode() );
		return result;
	}

	@Override
	public boolean equals( Object obj ) {
		if ( this == obj )
			return true;
		if ( obj == null )
			return false;
		if ( getClass() != obj.getClass() )
			return false;
		NotaFactura other = (NotaFactura) obj;
		if ( calle == null ) {
			if ( other.calle != null )
				return false;
		} else if ( !calle.equals( other.calle ) )
			return false;
		if ( codigopostal == null ) {
			if ( other.codigopostal != null )
				return false;
		} else if ( !codigopostal.equals( other.codigopostal ) )
			return false;
		if ( colonia == null ) {
			if ( other.colonia != null )
				return false;
		} else if ( !colonia.equals( other.colonia ) )
			return false;
		if ( email == null ) {
			if ( other.email != null )
				return false;
		} else if ( !email.equals( other.email ) )
			return false;
		if ( estado == null ) {
			if ( other.estado != null )
				return false;
		} else if ( !estado.equals( other.estado ) )
			return false;
		if ( estatus == null ) {
			if ( other.estatus != null )
				return false;
		} else if ( !estatus.equals( other.estatus ) )
			return false;
		if ( factura == null ) {
			if ( other.factura != null )
				return false;
		} else if ( !factura.equals( other.factura ) )
			return false;
		if ( facturaOri == null ) {
			if ( other.facturaOri != null )
				return false;
		} else if ( !facturaOri.equals( other.facturaOri ) )
			return false;
		if ( fechaImpresion == null ) {
			if ( other.fechaImpresion != null )
				return false;
		} else if ( !fechaImpresion.equals( other.fechaImpresion ) )
			return false;
		if ( fechaMod == null ) {
			if ( other.fechaMod != null )
				return false;
		} else if ( !fechaMod.equals( other.fechaMod ) )
			return false;
		if ( formaPago == null ) {
			if ( other.formaPago != null )
				return false;
		} else if ( !formaPago.equals( other.formaPago ) )
			return false;
		if ( idCliente == null ) {
			if ( other.idCliente != null )
				return false;
		} else if ( !idCliente.equals( other.idCliente ) )
			return false;
		if ( idEmpleado == null ) {
			if ( other.idEmpleado != null )
				return false;
		} else if ( !idEmpleado.equals( other.idEmpleado ) )
			return false;
		if ( idFactura == null ) {
			if ( other.idFactura != null )
				return false;
		} else if ( !idFactura.equals( other.idFactura ) )
			return false;
		if ( idFiscal == null ) {
			if ( other.idFiscal != null )
				return false;
		} else if ( !idFiscal.equals( other.idFiscal ) )
			return false;
		if ( importe == null ) {
			if ( other.importe != null )
				return false;
		} else if ( !importe.equals( other.importe ) )
			return false;
		if ( localidad == null ) {
			if ( other.localidad != null )
				return false;
		} else if ( !localidad.equals( other.localidad ) )
			return false;
		if ( metodoPago == null ) {
			if ( other.metodoPago != null )
				return false;
		} else if ( !metodoPago.equals( other.metodoPago ) )
			return false;
		if ( municipio == null ) {
			if ( other.municipio != null )
				return false;
		} else if ( !municipio.equals( other.municipio ) )
			return false;
		if ( noexterior == null ) {
			if ( other.noexterior != null )
				return false;
		} else if ( !noexterior.equals( other.noexterior ) )
			return false;
		if ( nointerior == null ) {
			if ( other.nointerior != null )
				return false;
		} else if ( !nointerior.equals( other.nointerior ) )
			return false;
		if ( nombre == null ) {
			if ( other.nombre != null )
				return false;
		} else if ( !nombre.equals( other.nombre ) )
			return false;
		if ( observaciones == null ) {
			if ( other.observaciones != null )
				return false;
		} else if ( !observaciones.equals( other.observaciones ) )
			return false;
		if ( paciente == null ) {
			if ( other.paciente != null )
				return false;
		} else if ( !paciente.equals( other.paciente ) )
			return false;
		if ( pais == null ) {
			if ( other.pais != null )
				return false;
		} else if ( !pais.equals( other.pais ) )
			return false;
		if ( razon == null ) {
			if ( other.razon != null )
				return false;
		} else if ( !razon.equals( other.razon ) )
			return false;
		if ( referencia == null ) {
			if ( other.referencia != null )
				return false;
		} else if ( !referencia.equals( other.referencia ) )
			return false;
		if ( rfc == null ) {
			if ( other.rfc != null )
				return false;
		} else if ( !rfc.equals( other.rfc ) )
			return false;
		if ( rx == null ) {
			if ( other.rx != null )
				return false;
		} else if ( !rx.equals( other.rx ) )
			return false;
		if ( ticket == null ) {
			if ( other.ticket != null )
				return false;
		} else if ( !ticket.equals( other.ticket ) )
			return false;
		if ( tipo == null ) {
			if ( other.tipo != null )
				return false;
		} else if ( !tipo.equals( other.tipo ) )
			return false;
		if ( tipoFac == null ) {
			if ( other.tipoFac != null )
				return false;
		} else if ( !tipoFac.equals( other.tipoFac ) )
			return false;
		if ( url == null ) {
			if ( other.url != null )
				return false;
		} else if ( !url.equals( other.url ) )
			return false;
		if ( xml == null ) {
			if ( other.xml != null )
				return false;
		} else if ( !xml.equals( other.xml ) )
			return false;
		return true;
	}

}
