package mx.com.lux.control.trabajos.data.vo;
// default package
// Generated 6/09/2011 02:19:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos implements java.io.Serializable {

	private int idPago;
	private String idFactura;
	private String idBanco;
	private String idFormaPago;
	private Character tipoPago;
	private String referenciaPago;
	private String montoPago;
	private Date fechaPago;
	private String idEmpleado;
	private char idSync;
	private Date fechaMod;
	private String idMod;
	private int idSucursal;
	private String idRecibo;
	private String parcialidad;
	private String idFPago;
	private String claveP;
	private String refClave;
	private String idBancoEmi;
	private String idTerm;
	private String idPlan;
	private boolean confirm;
	private double porDev;

	public Pagos() {
	}

	public Pagos( int idPago, Date fechaPago, char idSync, Date fechaMod, String idMod, int idSucursal, boolean confirm, double porDev ) {
		this.idPago = idPago;
		this.fechaPago = fechaPago;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.idSucursal = idSucursal;
		this.confirm = confirm;
		this.porDev = porDev;
	}

	public Pagos( int idPago, String idFactura, String idBanco, String idFormaPago, Character tipoPago, String referenciaPago, String montoPago, Date fechaPago, String idEmpleado, char idSync, Date fechaMod, String idMod, int idSucursal, String idRecibo, String parcialidad, String idFPago, String claveP, String refClave, String idBancoEmi, String idTerm, String idPlan, boolean confirm, double porDev ) {
		this.idPago = idPago;
		this.idFactura = idFactura;
		this.idBanco = idBanco;
		this.idFormaPago = idFormaPago;
		this.tipoPago = tipoPago;
		this.referenciaPago = referenciaPago;
		this.montoPago = montoPago;
		this.fechaPago = fechaPago;
		this.idEmpleado = idEmpleado;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.idSucursal = idSucursal;
		this.idRecibo = idRecibo;
		this.parcialidad = parcialidad;
		this.idFPago = idFPago;
		this.claveP = claveP;
		this.refClave = refClave;
		this.idBancoEmi = idBancoEmi;
		this.idTerm = idTerm;
		this.idPlan = idPlan;
		this.confirm = confirm;
		this.porDev = porDev;
	}

	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago( int idPago ) {
		this.idPago = idPago;
	}

	public String getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura( String idFactura ) {
		this.idFactura = idFactura;
	}

	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco( String idBanco ) {
		this.idBanco = idBanco;
	}

	public String getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago( String idFormaPago ) {
		this.idFormaPago = idFormaPago;
	}

	public Character getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago( Character tipoPago ) {
		this.tipoPago = tipoPago;
	}

	public String getReferenciaPago() {
		return this.referenciaPago;
	}

	public void setReferenciaPago( String referenciaPago ) {
		this.referenciaPago = referenciaPago;
	}

	public String getMontoPago() {
		return this.montoPago;
	}

	public void setMontoPago( String montoPago ) {
		this.montoPago = montoPago;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago( Date fechaPago ) {
		this.fechaPago = fechaPago;
	}

	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado( String idEmpleado ) {
		this.idEmpleado = idEmpleado;
	}

	public char getIdSync() {
		return this.idSync;
	}

	public void setIdSync( char idSync ) {
		this.idSync = idSync;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public int getIdSucursal() {
		return this.idSucursal;
	}

	public void setIdSucursal( int idSucursal ) {
		this.idSucursal = idSucursal;
	}

	public String getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo( String idRecibo ) {
		this.idRecibo = idRecibo;
	}

	public String getParcialidad() {
		return this.parcialidad;
	}

	public void setParcialidad( String parcialidad ) {
		this.parcialidad = parcialidad;
	}

	public String getIdFPago() {
		return this.idFPago;
	}

	public void setIdFPago( String idFPago ) {
		this.idFPago = idFPago;
	}

	public String getClaveP() {
		return this.claveP;
	}

	public void setClaveP( String claveP ) {
		this.claveP = claveP;
	}

	public String getRefClave() {
		return this.refClave;
	}

	public void setRefClave( String refClave ) {
		this.refClave = refClave;
	}

	public String getIdBancoEmi() {
		return this.idBancoEmi;
	}

	public void setIdBancoEmi( String idBancoEmi ) {
		this.idBancoEmi = idBancoEmi;
	}

	public String getIdTerm() {
		return this.idTerm;
	}

	public void setIdTerm( String idTerm ) {
		this.idTerm = idTerm;
	}

	public String getIdPlan() {
		return this.idPlan;
	}

	public void setIdPlan( String idPlan ) {
		this.idPlan = idPlan;
	}

	public boolean isConfirm() {
		return this.confirm;
	}

	public void setConfirm( boolean confirm ) {
		this.confirm = confirm;
	}

	public double getPorDev() {
		return this.porDev;
	}

	public void setPorDev( double porDev ) {
		this.porDev = porDev;
	}

}
