package mx.com.lux.control.trabajos.data.vo;

// Generated 21/07/2011 02:01:22 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal implements Serializable {

	private static final long serialVersionUID = -2667257045722268954L;

	private int idSucursal;
	private String nombre;
	private String direccion;
	private String colonia;
	private String localidad;
	private String idEstado;
	private String cp;
	private String telefonos;
	private String idGerente;
	private Integer letraAscii;
	private Integer numFactura;
	private Boolean sears;
	private Integer por100Anticipo;
	private Boolean impresionFact;
	private Integer serieRepVentas;
	private Integer numRepVentas;
	private Boolean serieNumOrden;
	private char idSync;
	private Date fechaMod;
	private String idMod;
	private String centroCostos;
	private String ciudad;
	private boolean domingo;

	public Sucursal() {
	}

	public Sucursal( int idSucursal, char idSync, Date fechaMod, String idMod, boolean domingo ) {
		this.idSucursal = idSucursal;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.domingo = domingo;
	}

	public Sucursal( int idSucursal, String nombre, String direccion, String colonia, String localidad, String idEstado, String cp, String telefonos, String idGerente, Integer letraAscii, Integer numFactura, Boolean sears, Integer por100Anticipo, Boolean impresionFact, Integer serieRepVentas, Integer numRepVentas, Boolean serieNumOrden, char idSync, Date fechaMod, String idMod, String centroCostos, String ciudad, boolean domingo ) {
		this.idSucursal = idSucursal;
		this.nombre = nombre;
		this.direccion = direccion;
		this.colonia = colonia;
		this.localidad = localidad;
		this.idEstado = idEstado;
		this.cp = cp;
		this.telefonos = telefonos;
		this.idGerente = idGerente;
		this.letraAscii = letraAscii;
		this.numFactura = numFactura;
		this.sears = sears;
		this.por100Anticipo = por100Anticipo;
		this.impresionFact = impresionFact;
		this.serieRepVentas = serieRepVentas;
		this.numRepVentas = numRepVentas;
		this.serieNumOrden = serieNumOrden;
		this.idSync = idSync;
		this.fechaMod = fechaMod;
		this.idMod = idMod;
		this.centroCostos = centroCostos;
		this.ciudad = ciudad;
		this.domingo = domingo;
	}

	public int getIdSucursal() {
		return this.idSucursal;
	}

	public String idSucursal() {
		return Integer.toString( idSucursal );
	}

	public void setIdSucursal( int idSucursal ) {
		this.idSucursal = idSucursal;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre( String nombre ) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion( String direccion ) {
		this.direccion = direccion;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia( String colonia ) {
		this.colonia = colonia;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad( String localidad ) {
		this.localidad = localidad;
	}

	public String getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado( String idEstado ) {
		this.idEstado = idEstado;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp( String cp ) {
		this.cp = cp;
	}

	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos( String telefonos ) {
		this.telefonos = telefonos;
	}

	public String getIdGerente() {
		return this.idGerente;
	}

	public void setIdGerente( String idGerente ) {
		this.idGerente = idGerente;
	}

	public Integer getLetraAscii() {
		return this.letraAscii;
	}

	public void setLetraAscii( Integer letraAscii ) {
		this.letraAscii = letraAscii;
	}

	public Integer getNumFactura() {
		return this.numFactura;
	}

	public void setNumFactura( Integer numFactura ) {
		this.numFactura = numFactura;
	}

	public Boolean getSears() {
		return this.sears;
	}

	public void setSears( Boolean sears ) {
		this.sears = sears;
	}

	public Integer getPor100Anticipo() {
		return this.por100Anticipo;
	}

	public void setPor100Anticipo( Integer por100Anticipo ) {
		this.por100Anticipo = por100Anticipo;
	}

	public Boolean getImpresionFact() {
		return this.impresionFact;
	}

	public void setImpresionFact( Boolean impresionFact ) {
		this.impresionFact = impresionFact;
	}

	public Integer getSerieRepVentas() {
		return this.serieRepVentas;
	}

	public void setSerieRepVentas( Integer serieRepVentas ) {
		this.serieRepVentas = serieRepVentas;
	}

	public Integer getNumRepVentas() {
		return this.numRepVentas;
	}

	public void setNumRepVentas( Integer numRepVentas ) {
		this.numRepVentas = numRepVentas;
	}

	public Boolean getSerieNumOrden() {
		return this.serieNumOrden;
	}

	public void setSerieNumOrden( Boolean serieNumOrden ) {
		this.serieNumOrden = serieNumOrden;
	}

	public char getIdSync() {
		return this.idSync;
	}

	public void setIdSync( char idSync ) {
		this.idSync = idSync;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod( Date fechaMod ) {
		this.fechaMod = fechaMod;
	}

	public String getIdMod() {
		return this.idMod;
	}

	public void setIdMod( String idMod ) {
		this.idMod = idMod;
	}

	public String getCentroCostos() {
		return this.centroCostos;
	}

	public void setCentroCostos( String centroCostos ) {
		this.centroCostos = centroCostos;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad( String ciudad ) {
		this.ciudad = ciudad;
	}

	public boolean isDomingo() {
		return this.domingo;
	}

	public void setDomingo( boolean domingo ) {
		this.domingo = domingo;
	}

}
